### ISSUE TITLE
Recognise hand gestures

### ISSUE THREAD

**Issue by 11acc** [sarwari-mallela/Map-Navigation-Using-Hand-Gestures#2]
Use mediapipes to recognise some hand gestures. Maybe we need another library to detect the hand gestures themselves?

**Comment by sarwari-mallela** [comment]
This is already done. The hand_tracking.py recognizes the hand and returns the positions of various points of the hand like fingertips, wrist, etc.

**Comment by sarwari-mallela** [comment]
Done
