### ISSUE TITLE
Hand gestures for map movement

### ISSUE THREAD

**Issue by 11acc** [sarwari-mallela/Map-Navigation-Using-Hand-Gestures#3]
What hand gestures are we going to use to pan, zoom, etc.. ?

They have to be intuitive, aka no instructions needed

**Comment by solsylph** [comment]
![image](https://github.com/sarwari-mallela/Map-Navigation-Using-Hand-Gestures/assets/126614634/6fc8d09d-6651-4d2b-ac10-e9782340481b)
zoom in 
![image](https://github.com/sarwari-mallela/Map-Navigation-Using-Hand-Gestures/assets/126614634/da1fc942-cfad-4332-8dbf-4b3348c12f79)
zoom out
![image](https://github.com/sarwari-mallela/Map-Navigation-Using-Hand-Gestures/assets/126614634/4eb3011b-beb4-43b4-a0fb-4bd09076987c)
default gesture

**Comment by 11acc** [comment]
Reopening for incomplete implementation

**Comment by 11acc** [comment]
forgot to close this lol
works well :)
